### ISSUE TITLE
File names with name "++ " and other text raises error

### ISSUE THREAD

**Issue by dgreen** [RainCat1998/obsidian-custom-attachment-location#61]
Having a ++ But - Obsidian does not like ++ in a title causes error.  It is the leading ++ that causes the problem.

I use + Title  and ++ Title to make those files float to top of the list in a sorted view.

The console log of Obsidian shows

```
SyntaxError: Invalid regular expression: /^./_resources/++ Bug - Obsidian does not like ++ in title$/: Nothing to repeat (at plugin:obsidian-custom-attachment-location:4558:12)
    at new RegExp (<anonymous>)
    at CustomAttachmentLocationPlugin.interpolateToDigitRegex (plugin:obsidian-custom-attachment-location:4558:12)
    at CustomAttachmentLocationPlugin.getEarliestAttachmentFolder (plugin:obsidian-custom-attachment-location:4584:30)
    at CustomAttachmentLocationPlugin.getAttachmentFolderPath (plugin:obsidian-custom-attachment-location:4600:23)
    at CustomAttachmentLocationPlugin.handleFileOpen (plugin:obsidian-custom-attachment-location:4697:29)
    at eval (plugin:obsidian-custom-attachment-location:4492:41)
    at e.tryTrigger (app.js:1:723190)
    at e.trigger (app.js:1:723123)
    at t.trigger (app.js:1:2283688)
    at t.activeLeafEvents (app.js:1:2269215)
    at l (app.js:1:522936)
    at c (app.js:1:523052)
```

**Comment by mnaoumov** [comment]
@dgreen Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/1.1.0
