### ISSUE TITLE
Plugin 'Failed to load' on Android

### ISSUE THREAD

**Issue by manycrumbs** [RainCat1998/obsidian-custom-attachment-location#86]
Hi, I'm using the latest version of Obsidian on both Mac and Android (v1.6.7) and whilst the plugin loads successfully on desktop, it repeatedly fails to load on mobile. Other plugins load correctly on mobile. I notice in the changelog for this plugin that mobile support was added in the past? Should it work, or have I missed that it's desktop only?

So far I've unsuccessfully tried:
1. Enabling the plugin on the desktop version and pushing the config to mobile
2. Creating a new vault
3. Using a different mobile device with a fresh install of obsidian and no changes other than installing the plugin
4. Downgrade the plugin by a few versions

Happy to try and help troubleshoot this if it should be working

**Comment by manycrumbs** [comment]
Connecting the phone to Google Chrome and inspecting Obsidian, when trying to enable the plugin the Obsidian Developer Console outputs:

`Plugin failure: obsidian-custom-attachment-location TypeError: Cannot read properties of undefined (reading 'pathToFileURL')
    at eval (plugin:obsidian-custom-attachment-location:65:90)
    at node_modules/obsidian-dev-utils/dist/lib/obsidian/Plugin/PluginSettings.cjs (plugin:obsidian-custom-attachment-location:65:117)
    at __require (plugin:obsidian-custom-attachment-location:14:50)
    at anonymous (plugin:obsidian-custom-attachment-location:6594:37)
    at e.<anonymous> (app.js:1:2274677)
    at app.js:1:237136
    at Object.next (app.js:1:237241)
    at a (app.js:1:235959)`

**Comment by mnaoumov** [comment]
Fixed in https://github.com/RainCat1998/obsidian-custom-attachment-location/releases/tag/4.10.0

**Comment by manycrumbs** [comment]
Thank you!
